#ifndef __RCC_REG_H__
#define __RCC_REG_H__

#define RCC_REG_BASE 0x40021000

#define RCC_CR (RCC_REG_BASE+0x0)
#define RCC_CFGR (RCC_REG_BASE+0x4)
#define RCC_CIR  (RCC_REG_BASE+0x8)
#define RCC_APB2RSTR (RCC_REG_BASE+0xc)
#define RCC_APB1RSTR (RCC_REG_BASE+0x10)
#define RCC_AHBENR (RCC_REG_BASE+0x14)
#define RCC_APB2ENR (RCC_REG_BASE+0x18)
#define RCC_APB1ENR (RCC_REG_BASE+0x1c)
#define RCC_BDCR (RCC_REG_BASE+0x20)
#define RCC_CSR (RCC_REG_BASE+0x24)



#endif
